### ISSUE TITLE
dfs0 - Wrong DataValueType saved for DataValueType.MeanStepBackward and  DataValueType.MeanStepForward 

### ISSUE THREAD

**Issue by haugwitz** [DHI/mikeio#141]
When setting Datatype meanstepBackward it seems the timeseries is saved as MeanStepAccumulated.
Same goes for: MeanStepForward becomes Reverse Mean StepAccumulated.

If using Instantaneous or Accumulated it is saved correctly.

We apply the datavaluetype as follows:

dataValueType = DataValueType.MeanStepBackward

for rows in range(0,NumRows):

            DataTypeList.append(DataValuetype)

 df.to_dfs0(filePath[0], items=Items, data_value_type = DataTypeList)

We had expected the file to have the MeanStep Backward value type when opening the file in MikeSHE

I have mike SDK 2019 installed.

**Comment by laurafroelich** [comment]
It seems this is due to a difference in terminology, and meanstepBackward is another term for MeanStepAccumulated. Likewise for MeanStepForward and Reverse Mean StepAccumulated. In MIKE SDK 2019, the terms Instantaneous, Accumulated, StepAccumulated, MeanStepBackward, and MeanStepForward are used (see http://doc.mikepoweredbydhi.help/webhelp/2019/DHI_DFS/html/T_DHI_Generic_MikeZero_DFS_DataValueType.htm and https://manuals.mikepoweredbydhi.help/2019/General/SDK_UserGuide.pdf).

What version of MIKE SHE was the file opened in? It would be good to check the documentation for that version to see that the definition of meanstepBackward matches that for MeanStepAccumulated and the definition of MeanStepForward matches that for Reverse Mean StepAccumulated.

**Comment by haugwitz** [comment]
Hi Laura Thanks. 

Yeah I was doing this for someone else and was not aware that they are just different names for the same thing.

Im using MikeZero 2019 and SDK 2019

So in in my GUI I will just use the terminology used in MikeZero to make seem correct. 

It would make sense though to use the same terminology in the SDK and the main program. Would it be the same if I updated both to 2020?

**Comment by laurafroelich** [comment]
I believe the terms Instantaneous, Accumulated, StepAccumulated, MeanStepBackward, and MeanStepForward are the newer ones, and expect these to be used in newer releases.

Did this answer the question so we can close the issue?

**Comment by haugwitz** [comment]
Yes thank you. I will inform my colleagues that it will be corrected in Mike Zero.
