### ISSUE TITLE
Contributor guidelines

### ISSUE THREAD

**Issue by rhaDHI** [DHI/mikeio#17]
There is a visual studio project, but with outdated file references and doesn't seem to be able run tests. 
How do you setup the code in Visual Studio to also include the tests? Also guidelines for setting up the required python environment is missing, e.g. a dev requirements txt?
Please add a few lines in the readme about setting up this environment for contributing if you already know how.

**Comment by j08lue** [comment]
For testing, you could consider using `pytest` instead of something in VS. GitHub Actions is the new kid on the block for CI and makes it easy to use your custom (MIKE-prepared) Docker environment for running your tests.

Alternatively, @Robert-OP already has good experience in hooking up Azure DevOps Pipelines to GitHub repos.

**Comment by rhaDHI** [comment]
Cool. I could run all tests in PyCharm using pytest :-) I was just wondering if this was also setup in VS already.

**Comment by ecomodeller** [comment]
I run pytest from the command line, but it works in VS Code as well.
![testing](https://user-images.githubusercontent.com/614215/75321238-9eade780-5870-11ea-9cea-979222d1c33b.png)
