### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by j08lue** [DHI/mikeio#2]
How about calling the package (and repo) `dfspy`? Then the scope is more apparent - DFS file IO.

There is only one [existing repo with that name](https://github.com/jason-r-becker/dfspy) and that is impossible to mix up with ours is and, most importantly, it is [not on PyPI](https://pypi.org/search/?q=dfspy).

**Comment by jsmariegaard** [comment]
I think it's a good idea to remove DHI from the name

**Comment by ecomodeller** [comment]
How about `mikeio` ?

Dfs is a bit overloaded term (e.g. Distributed File System)

**Comment by FranzThomsen1089** [comment]
how about mikecore ... that's what the corresponding C# NuGet package is called

**Comment by j08lue** [comment]
@FranzThomsen1089 good call with using same names for same things! However, `mikecore` sounds to me like, well, the core of MIKE (models), which this is not. In fact, just a help for pre/post-processing of files. But name preferences are obviously very subjective... 

@ecomodeller `mikeio` is also more like a component of a model (the I/O part). But this choice of name could be justified by the fact that this library, in a way, interfaces with exactly that component.

Since you put so much work into the code, @ecomodeller, I think you should just decide.

**Comment by jsmariegaard** [comment]
I agree with you @j08lue, I don't think mikecore is the best term, since there is already something else called that (and this is not an official MIKE package). mikeio is cute and nice because you can pronounce it but still I would prefer something which is contains dfs (eventhough the term is a bit overloaded) since that is exactly what is does: handle input/output to dfs files. For me MIKE is more the models. I would prefer pydfs, dfspy or similar, but also think that @ecomodeller and @marcridler  should make the decision. 
Greetings from Melbourne :-)

**Comment by ecomodeller** [comment]
renamed to mikeio
