### ISSUE TITLE
PFS. read write of parameter list, which contains both boolean and string

### ISSUE THREAD

**Issue by jsmariegaard** [DHI/mikeio#437]
MIKE IO version 1.2.dev0

This is probably a rare case, but it seems that this line will fail: 

    fill_list = false, 'TEST'

if you read it from a pfs file and try to write it again you will get this: 

    fill_list = 'false, 'TEST''

Which is different. This only occurs if the line contains both boolean and string.  

Here is another example: 

    fill_list = 0,'TEST',false

which gives

    fill_list = '0,'TEST',false'

Some other combined cases can be even worse(!) - the below line cannot be parsed: 

     fill_list = 'dsd', 0, 0.0, false

Gives this error:

      E           expected <block end>, but found ','
      E             in "<unicode string>", line 16, column 22:
      E                   fill_list:  'dsd', 0.0, false

Probably because the string is first on the line.

**Comment by ecomodeller** [comment]
The value of `fill_list` is an array and have to be encoded as an array in order to be parsed correctly as yaml.

So the trick is to convert the valid pfs line:
`fill_list = 'dsd', 0, 0.0, false`
to the the valid yaml line
`fill_list : ['dsd', 0, 0.0, false]`

And then it should work
![image](https://user-images.githubusercontent.com/614215/193517456-51775b0c-7b78-4ea6-928e-8c10644a0f46.png)

**Comment by jsmariegaard** [comment]
Great, @ecomodeller , will you open a PR and fix this ;-)
