### ISSUE TITLE
dfs file extension check only allows lower case extension ".dfs", fails for ".DFS"

### ISSUE THREAD

**Issue by watermain** [DHI/mikeio#455]
Trying to read a file with extension .DFS3 fails:

>>> fn = "C:/Users/uha/OneDrive - DHI/2022/Bugs/2022_10_20_OpenWell/OpenWell.she - Result Files/OpenWell_PreProcessed_3DSZ.DFS3"
>>> ds = mikeio.read(fn)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python310\lib\site-packages\mikeio\__init__.py", line 111, in read
    raise ValueError("mikeio.read() is only supported for Dfs files")

Works with [...]/OpenWell_PreProcessed_3DSZ.dfs3

**Comment by ecomodeller** [comment]
Hi @watermain, this should be easy for you to fix.

1. Fork the mikeio repo
2. take a look a the implementation of mikeio.read https://github.com/DHI/mikeio/blob/231b9cfd04dee2c90955acd01ef9583e0809c4f5/mikeio/__init__.py#L108-L110
3. Add a failing test
4. Change it so that it accepts filenames regardless of case
5. Submit a PR
