### ISSUE TITLE
How to modify .she file

### ISSUE THREAD

**Issue by lj512lj512** [DHI/mikeio#479]
I am trying to modify the .she file. For example, change SimulationPeriod, HotStartDateIndex, HotStartDate, etc.

But mikeio changed many things when I used it to read and write .she files. For example, the following codes: 

she_run_path = r'C:\Users\test_running.she'
pfs = mikeio.Pfs(she_run_path, unique_keywords=False)
pfs.write(r'C:\Users\test_running_new.she')  

There are a lot of lines that are different between test_running.she and test_running_new.she.

I also tried to change .she to .mfm as suggested in other issues, but it did not work. 

My MIKE Zero version is 2022, mikeio version is 1.2.4.

**Comment by jsmariegaard** [comment]
Hi @lj512lj512, MIKE SHE uses keywords and sections with the same names. This is difficult to handle using a dict as the data model - hence multiply-defined keywords/sections goes into a special list. This unfortunately also means that read-write often will not retain the _order_ of the elements inside a section (if the same name is present multiple times). So my guess would be that the differences you see are due to a bit of re-ordering in cases were the same name is present multiple times within a section. You could try to open both files in MIKE Zero and save them again and then check the difference. Are they still different?

**Comment by lj512lj512** [comment]
Hi Jasper @jsmariegaard.

Thank you. After I open-save .she file with MIKE Zero. They are the same, no difference.

But I need to modify .she file in a loop without opening it with MIKE Zero and save it again. Do you have any suggestions?

**Comment by jsmariegaard** [comment]
Hi again, opening in MIKE Zero and saving again was only to verify that the file indeed was the same (it will just re-order the elements inside the sections - this has no functional change). This is not something you need to do as part of your workflow :-)
