### ISSUE TITLE
Read more res1d quantity types

### ISSUE THREAD

**Issue by akzabel** [DHI/mikeio#56]
Hi, 
any chance that new DATA_TYPES_HANDLED_IN_QUERIES will be added soon?
In order to read result information of structures, I am missing the following:
- Discharge Combined Structure
- Gate level: (Underflow Gate)

& there is a typo in the Examples (Read Res1D file Return Pandas DataFrame):
 ts = **r1d**.read('res1dfile.res1d', queries)
vs. 
ts = **res1d**.read...

Thanks! Anna

**Comment by akzabel** [comment]
Great, could you also fix the typo on the website pls?
https://github.com/DHI/mikeio

**Comment by maximlt** [comment]
> 
> 
> Great, could you also fix the typo on the website pls?
> https://github.com/DHI/mikeio

It's gonna be fixed when my PR is merged by the maintainers.

**Comment by akzabel** [comment]
Any news on the first part of the Qs?

any chance that new DATA_TYPES_HANDLED_IN_QUERIES will be added soon?
In order to read result information of structures, I am missing the following:

Discharge Combined Structure
Gate level: (Underflow Gate)

Thanks, Anna

**Comment by maximlt** [comment]
Hi Anna,

I worked a little bit on the code handling res1d files. I don't have time to add anything more. I'm pretty sure that at some point the maintainers (DHI I guess) will improve it. In the meantime, if you can code some Python you could try to do it yourself, building on the existing file.

Cheers,
Maxime

**Comment by rhaDHI** [comment]
Hi @akzabel ,
Could you please provide an example res1d file that includes the quantities you would like to read? Then we can add the missing functionality and a test.
I guess what you would like is:
`query = res1d.QueryData('GateLevel', 'node1')`

I could find GateLevel on the official Mike1D PredefinedQuantity list. Is that the quantity you need? Maybe Discharge Combined Structure is called 'DischargeInStructure' on that list? We should be able to add all those quantities. 
/Rasmus

**Comment by rhaDHI** [comment]
@maximlt Is it enough to remove the [data type validation in the query class] (https://github.com/DHI/mikeio/blob/a6624ce7b8c6c29402e08463b9b6c5e749ae3862/mikeio/res1d.py#L367)
Any misspelled or unsupported data types will be caught later when checking for data types actually in the file. Then we don't need to expand the list if new quantities are added or change name.

**Comment by maximlt** [comment]
I think another change needs to be made because there's another use of `DATA_TYPES_HANDLED_IN_QUERIES` here:
https://github.com/DHI/mikeio/blob/a6624ce7b8c6c29402e08463b9b6c5e749ae3862/mikeio/res1d.py#L265

Of course validating the query could be done when checking the data types contained in the file, that's a good idea. Yet I believe it'd be nice to have somewhere a "list" of the types that can be retrieved, in the docs.

@akzabel in the mean time you could try to following:
First check what data is available in your file and find how it's called internally with:

```python
from mikeio import res1d

with res1d.open("file.res1d") as r1d:
    print(r1d.data_types)
```

Then add your data type to the list of handled types:
```python
DATA_TYPES_HANDLED_IN_QUERIES.append("GateLevel")  # If it's the right name
```

Now you should be able to run your query for this new data type.

As for discharge in structure, I think it'd require a little bit more work to the current implementation, it seems the data is stored in a different way:
https://github.com/DHI/mikeio/pull/45#issuecomment-635593794

Before improving the current code, I think it'd be nice to see to which extent the underlying SDK could be used to retrieve data, in order not to repeat code (and tests). It'd also be nice to have a more complex *resd1d* file in the test data.
