### ISSUE TITLE
Reorder dimension

### ISSUE THREAD

**Issue by ecomodeller** [DHI/mikeio#9]
At the moment the last dimension is time e.g. a  dfs2 has the following dimensions (y, x, nt).

How about moving them around to have the time axis first?

Dfs0: (t) 
Dfs1: (t, x)
Dfs2: (t, y, x)
Dfs3: (t, z, y, x)

**Comment by j08lue** [comment]
+1 from me, considering that band/time-first is the usual format with NetCDF climate data (cf `xarray`) and geospatial data formats (cf `rasterio`).

**Comment by jsmariegaard** [comment]
+1 from me; this is what all of them have in common

**Comment by marcridler** [comment]
+1 from me too.

**Comment by ecomodeller** [comment]
Done for dfs1, dfs2, dfsu. 
It remains to be done for dfs3 and I don't know about res1d. I never uses these files types. Something for @marcridler?

**Comment by jsmariegaard** [comment]
But why not 

Dfs0: (t)
Dfs1: (t, x)
Dfs2: (t, x, y)
Dfs3: (t, x, y, z)

Why would you want to axes in reverse order z, y, x?

**Comment by j08lue** [comment]
> Why would you want to axes in reverse order z, y, x

My reason would be that `(..., t, z, y, y)` is common practice for climate data stored in NetCDF, since the COARDS conventions from 1995:

> Order of dimensions:
> If any or all of the dimensions of a variable have the interpretations of "date or time" (a.k.a. "T"), "height or depth"(a.k.a. "Z"), "latitude" (a.k.a. "Y"), or "longitude" (a.k.a. "X") then those dimensions should appear in the relative order T, then Z, then Y, then X in the CDL definition corresponding to the file.
https://ferret.pmel.noaa.gov/Ferret/documentation/coards-netcdf-conventions

Although the more modern CF-conventions drop this constraint:

> This standard also relaxes the COARDS constraints on dimension order
http://cfconventions.org/cf-conventions/cf-conventions.html#_abstract

Also, geospatial images (GDAL formats like GeoTIFF) are usually stored in `(y, x)` order.
